### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by BernhardFuchs** [qcastel/github-actions-maven-release#33]
For us it is more more practical to use token-based authentictation rather than setting up a Deploy key for each repo, because we already have infrastructure for secret management available.  

My approach is to create a Personal Access Token with `Repo` permissions and use it in multiple repositories. I created a new kind of token which starts with `ghp_xxx` and added it to our secret management tool and pass it to the action via the `access-token` parameter. To my understanding this in turn gets assigned to the maven env variable `-Dusername` (can see this in the logs).  

During the `mvn release:prepare` phase maven tries to do a `git push` with the following command:

```
[INFO] Executing: /bin/sh -c cd /github/workspace && git push ***@github.com:<organization-name>/<repo-name>.git refs/heads/main:refs/heads/main
```

 and this results in following error message:

```
Error: 6,322 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project jsonld-common-java: Unable to commit files
Error: 6,323 [ERROR] Provider message:
Error: 6,323 [ERROR] The git-push command failed.
Error: 6,323 [ERROR] Command output:
Error: 6,323 [ERROR] Host key verification failed.
Error: 6,323 [ERROR] fatal: Could not read from remote repository.
Error: 6,323 [ERROR] 
Error: 6,323 [ERROR] Please make sure you have the correct access rights
Error: 6,323 [ERROR] and the repository exists.
```

I'm not sure if the format of the `github` url is correct, as it is partially masked. Maybe there is also some configuration of the action I got wrong.

**Comment by qcastel** [comment]
Hello @BernhardFuchs ,

Indeed, as you can see here, the only thing we do in this github action is to put the access token as the username: 
https://github.com/qcastel/docker-maven-release/blob/master/release.sh#L116

```
MAVEN_OPTION="$MAVEN_OPTION -Dusername=$GITREPO_ACCESS_TOKEN"
```
which comes from `access-token` as you said: https://github.com/qcastel/github-actions-maven-release/blob/master/action.yml#L144

Then we let maven release deal with the rest.

So far, I don't see what you did wrong.

Perhaps what I would try is to do the git push manually from a docker container, using the same token. This way you would be able to test your token and roll out from the possible error cause.

Although that said, `Host key verification failed.` sounds more like an SSH error than a permission.
Perhaps you setup the scm to use SSH instead of http? In the sample, we use SSH and therefore the SCM is 
```
		<url>git@github.com:qcastel/github-actions-maven-release-sample.git</url>
```
https://github.com/gh-a-sample/github-actions-maven-release-sample/blob/master/pom.xml#L25

For using token, I would except it to be:

```
<url>https://github.com/gh-a-sample/github-actions-maven-release-sample.git</url>
```
if that make sense.

```
For us it is more more practical to use token-based authentictation rather than setting up a Deploy key for each repo, because we already have infrastructure for secret management available.
```

personally I don't setup a deploy key on each repo but instead create a bot user and use the bot SSH key in the CI.
This way, all I need to do in each of my repo is to associate the bot to them. This has the additional value that I can sign the commits as the bot, making sure that the release is produced by a commit issued by the bot and therefore only from the CI.
It's a choice really, both solutions token or SSH are valid IMO.

**Comment by BernhardFuchs** [comment]
Thanks for your quick reply.  
The `scm` section in my pom looks like this:
```
	<scm>
		<url>https://github.com/decentralized-identity/jsonld-common-java</url>
		<connection>scm:git:git://github.com/decentralized-identity/jsonld-common-java.git</connection>
		<developerConnection>scm:git:git@github.com:decentralized-identity/jsonld-common-java.git</developerConnection>
	</scm>
```

It's an open source project, so feel free to check the logs at https://github.com/decentralized-identity/jsonld-common-java/runs/2457154957?check_suite_focus=true

**Comment by qcastel** [comment]
Try that https://github.com/decentralized-identity/jsonld-common-java/pull/3

**Comment by qcastel** [comment]
> Maybe the issue is with the ssh-key in the settings.xml

Not related: this is pushing to a private maven repo whereas your error is happening when pushing the bump version commit to the current git repository

**Comment by BernhardFuchs** [comment]
Thanks Quentin, using https on all `scm` propertiers solved the issue.
```
<url>https://github.com/decentralized-identity/jsonld-common-java</url>
<connection>scm:git:https://github.com/decentralized-identity/jsonld-common-java.git</connection>
<developerConnection>scm:git:https://github.com/decentralized-identity/jsonld-common-java.git</developerConnection>
```
