### ISSUE TITLE
old versions cannot be used any more

### ISSUE THREAD

**Issue by mwiede** [qcastel/github-actions-maven-release#7]
I was struggling with the upgrade from java 11 to 14.

I tried tag v0.1.0 but this message occurs:

```
Override the java home as gitactions is seting up the JAVA_HOME env variable
Do mvn release:prepare with arguments -Dgpg.passphrase=
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

This is because the JAVA_HOME is hard-coded in release.sh It's not a JRE, its just not there.

Same holds good for v1.8.0 and below.

**Comment by qcastel** [comment]
Hello @mwiede ,

You may have not wait for me to answer and use another solution since. 
I do have another project that is on Java 11 and working nicely.
It uses qcastel/github-actions-maven-release@master currently https://github.com/yapily/jose-database/blob/master/.github/workflows/release.yaml#L35
Although there is indeed a tag for this version, you should be able to make it works using the tag: `v1.11.1`
